
name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'  

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze Dart code
        run: flutter analyze

      - name: Run unit tests (if test dir exists)
        run: |
          if [ -d test ]; then flutter test; else echo "No test dir, skipping tests."; fi

      - name: Build APK (debug mode)
        run: flutter build apk --debug
