
name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Flutter (stable default)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Switch to Flutter beta channel + upgrade
        run: |
          flutter channel beta
          flutter upgrade

      - name: Enable Dart 3.7 SDK support
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze Dart code
        run: flutter analyze

      - name: Run unit tests
        run: flutter test

      - name: Build APK (debug mode)
        run: flutter build apk --debug
